### PR TITLE
Create string[Marathi].xml

### PR DESCRIPTION
**Pull request by atharvaunde**
Added Marathi (India) translstion for the app!

### CODE REVIEW

**Comment by pavelpoley** [comment]
Hi, thank you for your effort! can you insert the strings.xml in suitable values folder, for example (values-ru for Russian)

**Comment by atharvaunde** [comment]
@pavelpoley I will make a folder and add

**Comment by pavelpoley** [comment]
Can you check this list and tell me what is the correct values folder, i will add manualy
https://github.com/championswimmer/android-locales

**Comment by atharvaunde** [comment]
values-mr
 is the correct folder. I have added tha same folder in my repo and made a
new PR

**Pull request closed without merging**
